<?php
/**
 * Database Model for "bar"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 23/10/2013 
 */
namespace application\nutsNBolts\model
{
	use application\nutsNBolts\model\base\Bar as BarBase;
	
	class Bar extends BarBase	
	{
		
	}
}
?>