<?php
/**
 * Database Model for "bottle_template"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 23/10/2013 
 */
namespace application\nutsNBolts\model
{
	use application\nutsNBolts\model\base\BottleTemplate as BottleTemplateBase;
	
	class BottleTemplate extends BottleTemplateBase	
	{
		
	}
}
?>