<?php
/**
 * Database Model for "open_bottle"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 23/10/2013 
 */
namespace application\nutsNBolts\model
{
	use application\nutsNBolts\model\base\OpenBottle as OpenBottleBase;
	
	class OpenBottle extends OpenBottleBase	
	{
		
	}
}
?>