<?php
/**
 * Database Model for "subscribers"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 23/10/2013 
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\base\Subscribers as SubscribersBase;
	
	class Subscribers extends SubscribersBase	
	{
		
	}
}
?>