<?php
/**
 * Database Model for "bottle_by_bar"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 21/10/2013 
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class BottleByBar extends Base	
	{
		public $name		= 'bottle_by_bar';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(11) unsigned NOT NULL ' ,
			'bottle_id' => 'int(11)' ,
			'bar_id' => 'int(11)' ,
			'bottle_price' => 'double(15,2)' 
		);
	}
}
?>