<?php
/**
 * Database Model for "facebook"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
<<<<<<< Updated upstream
 * @since 01/10/2013 
=======
 * @since 02/10/2013 
>>>>>>> Stashed changes
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class Facebook extends Base	
	{
		public $name		= 'facebook';
		public $primary		= array();
		public $primary_ai	= false;
		public $autoCreate	= false;
		
		public $columns = array
		(

		);
	}
}
?>