<?php
/**
 * Database Model for "form_submission"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 14/08/2013 
 */
namespace application\nutsnbolts\model\base
{
	use application\nutsnbolts\model\common\Base;
	
	class FormSubmission extends Base	
	{
		public $name		= 'form_submission';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(10) NOT NULL ' ,
			'form_id' => 'int(10) NOT NULL ' ,
			'data' => 'text NOT NULL ' ,
			'exported' => 'tinyint(1) NOT NULL ' 
		);
	}
}
?>