<?php
/**
 * Database Model for "history"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 23/10/2013 
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class History extends Base	
	{
		public $name		= 'history';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(11) unsigned NOT NULL ' ,
			'open_bottle_id' => 'int(11)' ,
			'action' => 'varchar(20)' ,
			'date_action' => 'timestamp' ,
			'volume_remaining' => 'varchar(10)' 
		);
	}
}
?>