<?php
/**
 * Database Model for "message"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 11/10/2013 
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class Message extends Base	
	{
		public $name		= 'message';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(10) NOT NULL ' ,
			'from_user_id' => 'int(10) NOT NULL ' ,
			'to_user_id' => 'int(10) NOT NULL ' ,
			'subject' => 'varchar(200) NOT NULL ' ,
			'body' => 'text NOT NULL ' ,
			'status' => 'tinyint(1) NOT NULL ' 
		);
	}
}
?>