<?php
/**
 * Database Model for "node_comment"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 15/08/2013 
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class NodeComment extends Base	
	{
		public $name		= 'node_comment';
		public $primary		= array('id');
		public $primary_ai	= false;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(10) NOT NULL ' ,
			'node_id' => 'int(10) NOT NULL ' ,
			'user_id' => 'int(10) NOT NULL ' ,
			'name' => 'varchar(200) NOT NULL ' ,
			'body' => 'text NOT NULL ' 
		);
	}
}
?>