<?php
/**
 * Database Model for "open_bottle"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
<<<<<<< HEAD
 * @since 21/10/2013 
=======
 * @since 23/10/2013 
>>>>>>> refs/heads/dev.ego.isika
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class OpenBottle extends Base	
	{
		public $name		= 'open_bottle';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(11) unsigned NOT NULL ' ,
			'user_id' => 'int(11)' ,
			'bottle_by_bar_id' => 'int(11)' ,
			'bar_id' => 'int(11)' ,
			'date_opened' => 'timestamp' ,
<<<<<<< HEAD
			'bottle_price' => 'double(15,2)' 
=======
			'bottle_price' => 'double(15,2)' ,
			'volume_left' => 'int(10)' 
>>>>>>> refs/heads/dev.ego.isika
		);
	}
}
?>