<?php
/**
 * Database Model for "sms"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
<<<<<<< HEAD
 * @since 21/10/2013 
=======
 * @since 23/10/2013 
>>>>>>> refs/heads/dev.ego.isika
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class Sms extends Base	
	{
		public $name		= 'sms';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(11) unsigned NOT NULL ' ,
			'user_id' => 'int(11)' ,
			'date_sent' => 'timestamp' 
		);
	}
}
?>