<?php
/**
 * Database Model for "subscribers"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 11/08/2013 
 */
namespace application\nutsnbolts\model\base
{
	use application\nutsnbolts\model\common\Base;
	
	class Subscribers extends Base	
	{
		public $name		= 'subscribers';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(10) NOT NULL ' ,
			'fb_uid' => 'int(30) NOT NULL ' ,
			'email' => 'varchar(150)' ,
			'firstName' => 'varchar(200)' ,
			'lastName' => 'varchar(200)' ,
			'gender' => 'varchar(15)' ,
			'access_token' => 'text' ,
			'date_last_access_token' => 'datetime' ,
			'status' => 'int(1)' 
		);
	}
}
?>