<?php
/**
 * Database Model for "user"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 08/08/2013 
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class Subscriber extends Base	
	{
		public $name		= 'subscriber';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(10) NOT NULL ' ,
			'fb_uid' => 'int(30) NOT NULL ' ,
			'email' => 'varchar(150) NOT NULL ' ,
			'firstName' => 'varchar(100) NOT NULL ' ,
			'lastName' => 'varchar(100) NOT NULL ' ,
			'gender' => 'tinyint(1) NOT NULL ' ,
		);
	}
}
?>