<?php
/**
 * Database Model for "user_role"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 13/08/2013 
 */
namespace application\nutsnbolts\model\base
{
	use application\nutsnbolts\model\common\Base;
	
	class UserRole extends Base	
	{
		public $name		= 'user_role';
		public $primary		= array('user_id','role_id');
		public $primary_ai	= false;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'user_id' => 'int(10) NOT NULL ' ,
			'role_id' => 'int(10) NOT NULL ' 
		);
	}
}
?>