<?php
/**
 * Database Model for "user"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 11/10/2013 
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class User extends Base	
	{
		public $name		= 'user';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(10) NOT NULL ' ,
			'email' => 'varchar(150) NOT NULL ' ,
			'password' => 'varchar(100) NOT NULL ' ,
			'salt' => 'varchar(100) NOT NULL ' ,
			'name_first' => 'varchar(100) NOT NULL ' ,
			'name_last' => 'varchar(100) NOT NULL ' ,
			'phone' => 'varchar(50) NOT NULL ' ,
			'dob' => 'date NOT NULL ' ,
			'gender' => 'tinyint(1) NOT NULL ' ,
			'image' => 'varchar(200) NOT NULL ' ,
			'income_range' => 'varchar(20) NOT NULL ' ,
			'position' => 'varchar(200) NOT NULL ' ,
			'company' => 'varchar(200) NOT NULL ' ,
			'about' => 'varchar(1024) NOT NULL ' ,
			'date_created' => 'datetime NOT NULL ' ,
			'date_lastlogin' => 'datetime NOT NULL ' ,
			'date_lastactive' => 'datetime NOT NULL ' ,
			'status' => 'tinyint(1) NOT NULL ' 
		);
	}
}
?>