<?php
/**
 * Database Model for "workflow_transition_role"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
 * @since 10/10/2013 
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class WorkflowTransitionRole extends Base	
	{
		public $name		= 'workflow_transition_role';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(10) NOT NULL ' ,
			'transition_id' => 'int(10) NOT NULL ' ,
			'role_id' => 'int(10) NOT NULL ' 
		);
	}
}
?>