<?php
/**
 * Database Model for "workflow_step_transition"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @package application-model
<<<<<<< HEAD
 * @since 21/10/2013 
=======
 * @since 23/10/2013 
>>>>>>> refs/heads/dev.ego.isika
 */
namespace application\nutsNBolts\model\base
{
	use application\nutsNBolts\model\common\Base;
	
	class WorkflowStepTransition extends Base	
	{
		public $name		= 'workflow_step_transition';
		public $primary		= array('id');
		public $primary_ai	= true;
		public $autoCreate	= false;
		
		public $columns = array
		(
			'id' => 'int(10) NOT NULL ' ,
			'step_transition_id' => 'int(10) NOT NULL ' ,
			'action_id' => 'int(10) NOT NULL ' ,
			'params' => 'text NOT NULL ' ,
			'order' => 'int(5) NOT NULL ' 
		);
	}
}
?>