TRUNCATE TABLE `permission`;
TRUNCATE TABLE `permission_role`;


insert  into `permission`
(`key`,`name`,`description`,`category`)
values
('login','Login','Can Login.','Core'),
('admin.access','Access Admin Panel','Can access the admin panel after logging in.','Core'),
('admin.dashboard.create','Create Dashboard','Creates a new dashboard for a user','Dashboard'),
('admin.dashboard.read','Read Dashboard','','Dashboard'),
('admin.dashboard.update','Update Dashboard','','Dashboard'),
('admin.dashboard.delete','Delete Dashboard','','Dashboard'),
-- Settings
('admin.setting.nutsNBolts.read','Read Nuts n Bolts Settings','','Settings'),
('admin.setting.nutsNBolts.update','Update Nuts n Bolts Settings','','Settings'),
('admin.setting.site.create','Create Site Settings','','Settings'),
('admin.setting.site.read','Read Site Settings','','Settings'),
('admin.setting.site.update','Update Site Settings','','Settings'),
('admin.setting.site.delete','Delete Site Settings','','Settings'),
-- Users
('admin.user.create','Create Users','','User'),
('admin.user.read','Read Users','','User'),
('admin.user.update','Update Users','','User'),
('admin.user.delete','Delete Users','','User'),
('admin.user.impersonate','Impersonate User','','User'),
('user.messsage.create','Create Messages','','User'),
('user.messsage.read','Read Messages','','User'),
('user.messsage.update','Update Messages','','User'),
('user.messsage.delete','Delete Messages','','User'),
('user.profile.read','Read Profile','','User'),
('user.profile.update','Update Profile','','User'),
-- Security
('admin.permission.create','Create Roles','','Security'),
('admin.permission.read','Read Roles','','Security'),
('admin.permission.update','Update Roles','','Security'),
('admin.permission.delete','Delete Roles','','Security'),
('admin.role.create','Create Roles','','Security'),
('admin.role.read','Read Roles','','Security'),
('admin.role.update','Update Roles','','Security'),
('admin.role.delete','Delete Roles','','Security'),
('admin.policy.create','Create Policies','','Security'),
('admin.policy.read','Read Policies','','Security'),
('admin.policy.update','Update Policies','','Security'),
('admin.policy.delete','Delete Policies','','Security'),
('admin.policy.password.create','Create Password Policies','','Security'),
('admin.policy.password.read','Read Password Policies','','Security'),
('admin.policy.password.update','Update Password Policies','','Security'),
('admin.policy.password.delete','Delete Password Policies','','Security'),
-- Pages
('admin.page.create','Create Pages','','Page'),
('admin.page.read','Read Pages','','Page'),
('admin.page.update','Update Pages','','Page'),
('admin.page.delete','Delete Pages','','Page'),
('admin.pageType.create','Create Page Types','','Page'),
('admin.pageType.read','Read Page Types','','Page'),
('admin.pageType.update','Update Page Types','','Page'),
('admin.pageType.delete','Delete Page Types','','Page'),
-- Content
('admin.content.contentType.create','Create Content Types','','Content'),
('admin.content.contentType.read','Read Content Types','','Content'),
('admin.content.contentType.update','Update Content Types','','Content'),
('admin.content.contentType.delete','Delete Content Types','','Content'),
('admin.content.navigation.create','Create Navigations','','Content'),
('admin.content.navigation.read','Read Navigations','','Content'),
('admin.content.navigation.update','Update Navigations','','Content'),
('admin.content.navigation.delete','Delete Navigations','','Content'),
('admin.content.form.create','Create Forms','','Content'),
('admin.content.form.read','Read Forms','','Content'),
('admin.content.form.update','Update Forms','','Content'),
('admin.content.form.delete','Delete Forms','','Content'),
('admin.content.node.create','Create Nodes','','Content'),
('admin.content.node.read','Read Nodes','','Content'),
('admin.content.node.update','Update Nodes','','Content'),
('admin.content.node.delete','Delete Nodes','','Content'),
('admin.content.node.ownership','Change Node Ownership','','Content'),
('admin.content.node.archive','Archive Node','','Content'),
('admin.content.node.permit','Permit Access to Nodes','','Content'),
-- Subscriptions
('admin.subscription.package.create','Create Subscription Packages','','Subscriptions'),
('admin.subscription.package.read','Read Subscription Packages','','Subscriptions'),
('admin.subscription.package.update','Update Subscription Packages','','Subscriptions'),
('admin.subscription.package.delete','Delete Subscription Packages','','Subscriptions'),
('admin.subscription.subscriber.create','Create Subscription Subscribers','','Subscriptions'),
('admin.subscription.subscriber.read','Read Subscription Subscribers','','Subscriptions'),
('admin.subscription.subscriber.update','Update Subscription Subscribers','','Subscriptions'),
('admin.subscription.subscriber.delete','Delete Subscription Subscribers','','Subscriptions'),
-- Collections
('admin.collection.create','Create Collections','','Collections'),
('admin.collection.read','Read Collections','','Collections'),
('admin.collection.update','Update Collections','','Collections'),
('admin.collection.delete','Delete Collections','','Collections'),
-- Workflows
('admin.workflow.create','Create Workflows','','Workflow'),
('admin.workflow.read','Read Workflows','','Workflow'),
('admin.workflow.update','Update Workflows','','Workflow'),
('admin.workflow.delete','Delete Workflows','','Workflow');

