# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem 'middleman'
gem 'json', '~> 1.7.7'

if RUBY_PLATFORM =~ /linux/i
  gem 'rb-inotify', '~> 0.9'
end
